"""alarm_kolonu_kaldırıldı

Revision ID: 9029da62a066
Revises: c65efb826d32
Create Date: 2026-02-06 10:31:30.319406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9029da62a066'
down_revision = 'c65efb826d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('criminals', schema=None) as batch_op:
        batch_op.drop_column('alarm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('criminals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alarm', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
